/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Login200,
  LoginOrSignupWithOtp200,
  LoginOtpRequest,
  LoginRequest,
  RequestOtp200,
  RequestOtpLogin,
  Signup200,
  SignupRequest
} from '.././model';

import signupMutator from '../../utils/axiosInstance';
import requestOtpMutator from '../../utils/axiosInstance';
import loginMutator from '../../utils/axiosInstance';
import loginOrSignupWithOtpMutator from '../../utils/axiosInstance';




export const signup = (
    signupRequest: SignupRequest,
 signal?: AbortSignal
) => {
      
      
      return signupMutator<Signup200>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest, signal
    },
      );
    }
  


export const getSignupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signup(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
    export type SignupMutationBody = SignupRequest
    export type SignupMutationError = unknown

    export const useSignup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signup>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getSignupMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const requestOtp = (
    requestOtpLogin: RequestOtpLogin,
 signal?: AbortSignal
) => {
      
      
      return requestOtpMutator<RequestOtp200>(
      {url: `/api/auth/request-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestOtpLogin, signal
    },
      );
    }
  


export const getRequestOtpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestOtp>>, TError,{data: RequestOtpLogin}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof requestOtp>>, TError,{data: RequestOtpLogin}, TContext> => {

const mutationKey = ['requestOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestOtp>>, {data: RequestOtpLogin}> = (props) => {
          const {data} = props ?? {};

          return  requestOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestOtpMutationResult = NonNullable<Awaited<ReturnType<typeof requestOtp>>>
    export type RequestOtpMutationBody = RequestOtpLogin
    export type RequestOtpMutationError = unknown

    export const useRequestOtp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestOtp>>, TError,{data: RequestOtpLogin}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestOtp>>,
        TError,
        {data: RequestOtpLogin},
        TContext
      > => {

      const mutationOptions = getRequestOtpMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const login = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return loginMutator<Login200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = unknown

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const loginOrSignupWithOtp = (
    loginOtpRequest: LoginOtpRequest,
 signal?: AbortSignal
) => {
      
      
      return loginOrSignupWithOtpMutator<LoginOrSignupWithOtp200>(
      {url: `/api/auth/login-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginOtpRequest, signal
    },
      );
    }
  


export const getLoginOrSignupWithOtpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginOrSignupWithOtp>>, TError,{data: LoginOtpRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginOrSignupWithOtp>>, TError,{data: LoginOtpRequest}, TContext> => {

const mutationKey = ['loginOrSignupWithOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginOrSignupWithOtp>>, {data: LoginOtpRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginOrSignupWithOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginOrSignupWithOtpMutationResult = NonNullable<Awaited<ReturnType<typeof loginOrSignupWithOtp>>>
    export type LoginOrSignupWithOtpMutationBody = LoginOtpRequest
    export type LoginOrSignupWithOtpMutationError = unknown

    export const useLoginOrSignupWithOtp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginOrSignupWithOtp>>, TError,{data: LoginOtpRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginOrSignupWithOtp>>,
        TError,
        {data: LoginOtpRequest},
        TContext
      > => {

      const mutationOptions = getLoginOrSignupWithOtpMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    