/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface AddressInfo {
  address1?: string;
  address2?: string;
  company?: string;
  first_name?: string;
  last_name?: string;
  phone?: string;
  zip?: string;
  province_code?: string;
  country_code?: string;
  district_code?: string;
  ward_code?: string;
}
