/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CartItemDTO {
  id?: string;
  quantity?: number;
  price?: number;
  line_price?: number;
  variant_id?: number;
  product_id?: string;
  product_title?: string;
  variant_title?: string;
  sku?: string;
  image?: string;
  line?: number;
}
