/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CartChangeRequest {
  /** @minimum 1 */
  line: number;
  /** @minimum 0 */
  quantity: number;
}
