/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CartItemRequestProperties } from './cartItemRequestProperties';

export interface CartItemRequest {
  variant_id: number;
  product_id?: string;
  /** @minimum 1 */
  quantity: number;
  properties?: CartItemRequestProperties;
}
