/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CartItemViewProperties } from './cartItemViewProperties';

export interface CartItemView {
  properties?: CartItemViewProperties;
  id?: string;
  handle?: string;
  url?: string;
  title?: string;
  variant_id?: number;
  product_id?: string;
  quantity?: number;
  product_type?: string;
  barcode?: string;
  image?: string;
  vendor?: string;
  price?: number;
  sku?: string;
  grams?: number;
  variant_title?: string;
  line_price?: number;
  price_original?: number;
  gift_card?: boolean;
  requires_shipping?: boolean;
  not_allow_promotion?: boolean;
  line_price_original?: number;
  product_title?: string;
  variant_options?: string[];
}
