/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UtmParameters } from './utmParameters';
import type { LineItemView } from './lineItemView';
import type { ShippingMethodView } from './shippingMethodView';
import type { PaymentMethodView } from './paymentMethodView';
import type { DiscountAllocation } from './discountAllocation';
import type { CheckoutResponseViewAttributes } from './checkoutResponseViewAttributes';
import type { CustomerMembership } from './customerMembership';
import type { OrderView } from './orderView';
import type { EInvoiceInfo } from './eInvoiceInfo';

export interface CheckoutResponseView {
  id?: string;
  phone_country_code?: string;
  phone?: string;
  full_name?: string;
  email?: string;
  email_option?: number;
  shipping_address?: string;
  shipping_city?: string;
  shipping_zip_code?: string;
  shipping_company?: string;
  shipping_country_id?: number;
  shipping_province_id?: number;
  shipping_district_id?: number;
  shipping_ward_id?: number;
  shipping_method_id?: number;
  shipping_method_name?: string;
  payment_method_name?: string;
  payment_method_id?: number;
  pay_deposit_only?: boolean;
  deposit_required?: boolean;
  utm_parameters?: UtmParameters;
  deposit_amount?: number;
  deposit_codamount?: number;
  note?: string;
  requires_shipping?: boolean;
  created_at?: string;
  updated_at?: string;
  completed_at?: string;
  errors?: string[];
  warnings?: string[];
  user_errors?: string[];
  ready?: boolean;
  line_items?: LineItemView[];
  shipping_methods?: ShippingMethodView[];
  payment_methods?: PaymentMethodView[];
  discount_allocations?: DiscountAllocation[];
  gift_cards?: unknown[];
  attributes?: CheckoutResponseViewAttributes;
  discount?: number;
  location_id?: number;
  location_name?: string;
  location_country_id?: number;
  auth_email?: string;
  auth_phone?: string;
  auth_name?: string;
  customer_membership?: CustomerMembership;
  sub_total_before_tax?: number;
  sub_total_tax?: number;
  sub_total?: number;
  shipping_before_tax?: number;
  shipping_tax?: number;
  shipping?: number;
  total_tax_included?: number;
  total_tax_not_included?: number;
  total?: number;
  order?: OrderView;
  channel?: string;
  disallow_loyalty_program?: boolean;
  send_notify?: boolean;
  send_receipt?: boolean;
  allow_pick_at_location?: boolean;
  pick_at_location?: boolean;
  next_actions?: unknown;
  einvoice_info?: EInvoiceInfo;
  einvoice_request?: boolean;
}
