/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CartAttributeRequest } from './cartAttributeRequest';
import type { ShippingAddressRequest } from './shippingAddressRequest';

export interface CheckoutSessionRequest {
  /** @minItems 1 */
  attributes: CartAttributeRequest[];
  note?: string;
  email?: string;
  phoneNumber?: string;
  fullName?: string;
  shippingAddress?: ShippingAddressRequest;
  shippingMethodId?: number;
  paymentMethodId?: number;
}
