/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerAddressRequest } from './customerAddressRequest';

/**
 * Thông tin địa chỉ mới
 */
export type CreateCustomerAddress1Body = {[key: string]: CustomerAddressRequest};
