/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CreateRoleRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  description?: string;
  is_system?: boolean;
  permissions: string[];
}
