/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CollectRequest } from './collectRequest';

export interface CustomCollectionRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  title: string;
  body_html?: string;
  published?: boolean;
  sort_order?: string;
  template_suffix?: string;
  collects?: CollectRequest[];
}
