/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Thông tin chi tiết địa chỉ khách hàng
 */
export interface CustomerAddressView {
  /** Tên đầy đủ */
  name?: string;
  /** ID của địa chỉ */
  id?: string;
  /** Quốc gia */
  country?: string;
  /** Địa chỉ dòng 2 */
  address2?: string;
  /** Là địa chỉ mặc định */
  default?: boolean;
  /** Mã quận/huyện */
  district_code?: string;
  /** Họ */
  last_name?: string;
  /** Mã quốc gia */
  country_code?: string;
  /** Mã tỉnh/thành phố */
  province_code?: string;
  /** Mã phường/xã */
  ward_code?: string;
  /** Tên */
  first_name?: string;
  /** Địa chỉ dòng 1 */
  address1?: string;
  /** Số điện thoại */
  phone?: string;
  /** Tên công ty */
  company?: string;
  /** Phường/xã */
  ward?: string;
  /** Mã bưu điện */
  zip?: string;
  /** Thành phố */
  city?: string;
  /** Quận/huyện */
  district?: string;
  /** Tỉnh/thành phố */
  province?: string;
}
