/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CollectionImageView } from './collectionImageView';

export interface CustomCollectionView {
  id?: string;
  handle?: string;
  title?: string;
  created_at?: string;
  image?: CollectionImageView;
  published_at?: string;
  template_suffix?: string;
  published?: boolean;
  published_scope?: string;
  updated_at?: string;
  sort_order?: string;
  body_html?: string;
  items_count?: number;
}
