/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type CustomerSegmentViewType = typeof CustomerSegmentViewType[keyof typeof CustomerSegmentViewType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerSegmentViewType = {
  AUTOMATIC: 'AUTOMATIC',
  STATIC: 'STATIC',
} as const;
