/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerSegmentViewType } from './customerSegmentViewType';

export interface CustomerSegmentView {
  description?: string;
  name?: string;
  id?: number;
  type?: CustomerSegmentViewType;
  definition?: string;
  updatedDate?: string;
}
