/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerAddressView } from './customerAddressView';
import type { CustomerSegmentView } from './customerSegmentView';
import type { CustomerViewGender } from './customerViewGender';
import type { EInvoiceInfoView } from './eInvoiceInfoView';

export interface CustomerView {
  id?: string;
  tags?: string;
  addresses?: CustomerAddressView[];
  accepts_marketing?: boolean;
  note?: string;
  last_name?: string;
  segments?: CustomerSegmentView[];
  total_spent?: number;
  orders_count?: number;
  created_at?: string;
  first_name?: string;
  phone?: string;
  email?: string;
  gender?: CustomerViewGender;
  einvoice_info?: EInvoiceInfoView;
  group_name?: string;
  birthday?: string;
  avatar_url?: string;
  updated_at?: string;
  last_order_name?: string;
  last_order_date?: string;
  last_order_id?: string;
  total_paid?: number;
}
