/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Thông tin địa chỉ khách hàng
 */
export interface CustomerAddressRequest {
  /**
   * Địa chỉ dòng 1
   * @minLength 0
   * @maxLength 255
   */
  address1: string;
  /**
   * Địa chỉ dòng 2
   * @minLength 0
   * @maxLength 255
   */
  address2?: string;
  /**
   * Thành phố
   * @minLength 0
   * @maxLength 100
   */
  city?: string;
  /**
   * Tên
   * @minLength 0
   * @maxLength 100
   */
  first_name?: string;
  /**
   * Tên công ty
   * @minLength 0
   * @maxLength 255
   */
  company?: string;
  /**
   * Số điện thoại
   * @pattern ^[0-9+\-\s()]*$
   */
  phone?: string;
  /**
   * Họ
   * @minLength 0
   * @maxLength 100
   */
  last_name?: string;
  /**
   * Mã bưu điện
   * @minLength 0
   * @maxLength 20
   */
  zip?: string;
  /**
   * Mã tỉnh/thành phố
   * @minLength 0
   * @maxLength 10
   */
  province_code?: string;
  /**
   * Mã quốc gia
   * @minLength 0
   * @maxLength 10
   */
  country_code?: string;
  /**
   * Mã quận/huyện
   * @minLength 0
   * @maxLength 20
   */
  district_code?: string;
  /**
   * Mã phường/xã
   * @minLength 0
   * @maxLength 20
   */
  ward_code?: string;
  /** Đặt làm địa chỉ mặc định */
  is_default?: boolean;
}
