/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerRequestGender } from './customerRequestGender';
import type { CustomerAddressRequest } from './customerAddressRequest';
import type { EInvoiceInfoRequest } from './eInvoiceInfoRequest';

export interface CustomerRequest {
  is_accept_marketing?: boolean;
  email?: string;
  /** @pattern ^[0-9+\-\s()]+$ */
  phone?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  first_name?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  last_name?: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  note?: string;
  tags?: string;
  birthday?: string;
  gender?: CustomerRequestGender;
  addresses?: CustomerAddressRequest[];
  einvoice_info?: EInvoiceInfoRequest;
}
