/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type CustomerRequestGender = typeof CustomerRequestGender[keyof typeof CustomerRequestGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
