/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerMembership {
  tier?: string;
  accumulate_spent?: number;
  next_tier?: string;
  reward_point?: number;
  max_reward_point?: number;
  max_reward_amount?: number;
  earn_reward_point?: number;
  expire_date?: string;
}
