/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerProfileUpdateRequestGender } from './customerProfileUpdateRequestGender';

export interface CustomerProfileUpdateRequest {
  email?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  firstName?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  lastName?: string;
  birthday?: string;
  gender?: CustomerProfileUpdateRequestGender;
  avatar?: Blob;
}
