/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type CustomerProfileUpdateRequestGender = typeof CustomerProfileUpdateRequestGender[keyof typeof CustomerProfileUpdateRequestGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerProfileUpdateRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
