/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface DiscountAllocation {
  discount_id?: number;
  type?: string;
  name?: string;
  amount?: number;
  value_type?: number;
  value?: number;
  can_combine?: boolean;
}
