/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface EInvoiceInfo {
  company?: boolean;
  name?: string;
  tax_code?: string;
  address?: string;
  email?: string;
  save?: boolean;
  submit?: boolean;
}
