/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserView } from './userView';

export interface EmployeeView {
  id?: string;
  full_name?: string;
  user?: UserView;
  created_at?: string;
  updated_at?: string;
}
