/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface EmployeeGroupView {
  id?: string;
  type_id?: number;
  created_at?: string;
  employee_ids?: string[];
  group_name?: string;
  updated_at?: string;
}
