/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface EmployeeRequest {
  /**
   * @minLength 0
   * @maxLength 200
   */
  full_name: string;
}
