/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface EmployeeGroupRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  group_name: string;
  type_id: number;
  employee_ids?: string[];
}
