/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GenericFilterRequestFilters } from './genericFilterRequestFilters';

export interface GenericFilterRequest {
  /** @minimum 0 */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  sortProperty?: string;
  direction?: string;
  filters?: GenericFilterRequestFilters;
}
