/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type InviteUserRequestType = typeof InviteUserRequestType[keyof typeof InviteUserRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteUserRequestType = {
  user: 'user',
  employee: 'employee',
} as const;
