/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { InviteUserRequestType } from './inviteUserRequestType';

export interface InviteUserRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  username: string;
  type: InviteUserRequestType;
}
