/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DiscountAllocation } from './discountAllocation';

export interface LineItemView {
  id?: number;
  seq?: number;
  variant_id?: number;
  variant_type?: number;
  product_id?: number;
  product_title?: string;
  variant_title?: string;
  image_url?: string;
  price_original?: number;
  price?: number;
  line_price?: number;
  line_discount?: number;
  quantity?: number;
  weight?: number;
  line_weight?: number;
  line_tax?: number;
  line_amount?: number;
  available_quantity?: number;
  lot_support?: boolean;
  variant_unit_id?: number;
  unit_ratio?: number;
  unit?: string;
  requires_shipping?: boolean;
  not_allow_promotion?: boolean;
  discount_allocations?: DiscountAllocation[];
  attributes?: unknown[];
  components?: unknown;
}
