/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SimpleIdNameDTO } from './simpleIdNameDTO';

export interface ListSimpleIdNameDTO {
  empty?: boolean;
  lazy?: boolean;
  async?: boolean;
  traversableAgain?: boolean;
  sequential?: boolean;
  ordered?: boolean;
  distinct?: boolean;
  singleValued?: boolean;
  orNull?: SimpleIdNameDTO;
  memoized?: boolean;
}
