/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface LocationRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  location_name: string;
  address?: string;
  email?: string;
  address_cont?: string;
  phone?: string;
  street?: string;
  city?: string;
  country_id?: number;
  province_id?: number;
  postal_zip_code?: string;
  is_shipping_location: boolean;
  is_unavailable_qty?: boolean;
  latitude?: number;
  longitude?: number;
  district_id?: number;
  ward_id?: number;
  hold_stock?: boolean;
  user_ids?: number[];
  group_ids?: number[];
  type_id: number;
  area_id?: number;
  status?: number;
}
