/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface LocationView {
  name?: string;
  id?: string;
  address?: string;
  status?: number;
  is_unavailable_qty?: boolean;
  is_shipping_location?: boolean;
  type_id?: number;
  ward_code?: string;
  phone?: string;
  email?: string;
  city?: string;
  street?: string;
  user_ids?: number[];
  ward_id?: number;
  area_id?: number;
  country_name?: string;
  postal_zip_code?: string;
  hold_stock?: boolean;
  group_ids?: number[];
  province_id?: number;
  location_name?: string;
  longitude?: number;
  country_id?: number;
  district_id?: number;
  address_cont?: string;
  latitude?: number;
  ghn_hub_code?: string;
  address_display?: string;
  area_name?: string;
  gh_nv3_hub_code?: string;
  pro_ship_hub_code?: string;
  flex_ship_hub_code?: string;
  dhl_hub_code?: string;
  ghtk_hub_code?: string;
  district_name?: string;
  province_name?: string;
  ward_name?: string;
  viettel_post_hub_code?: string;
  viettel_post2018_hub_code?: string;
  ship_chung_hub_code?: string;
  is_primary_location?: boolean;
}
