/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderViewFinancialStatus = typeof OrderViewFinancialStatus[keyof typeof OrderViewFinancialStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderViewFinancialStatus = {
  pending: 'pending',
  authorized: 'authorized',
  partially_paid: 'partially_paid',
  paid: 'paid',
  partially_refunded: 'partially_refunded',
  refunded: 'refunded',
  voided: 'voided',
} as const;
