/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { AddressInfo } from './addressInfo';
import type { DiscountCode } from './discountCode';
import type { LineItem } from './lineItem';
import type { ShippingLine } from './shippingLine';
import type { NoteAttribute } from './noteAttribute';

export interface OrderInfo {
  billing_address?: AddressInfo;
  discount_codes?: DiscountCode[];
  /** @minLength 1 */
  email: string;
  tags?: string;
  gateway?: string;
  landing_site?: string;
  landing_site_ref?: string;
  source?: string;
  /** @minItems 1 */
  line_items: LineItem[];
  note?: string;
  referring_site?: string;
  shipping_address?: AddressInfo;
  shipping_lines?: ShippingLine[];
  source_name?: string;
  note_attributes?: NoteAttribute[];
  user_id?: string;
  location_id?: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_term?: string;
  utm_content?: string;
}
