/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderViewClosedStatus = typeof OrderViewClosedStatus[keyof typeof OrderViewClosedStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderViewClosedStatus = {
  unclosed: 'unclosed',
  closed: 'closed',
} as const;
