/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface OrderTransactionView {
  id?: string;
  currency?: string;
  parent_id?: string;
  status?: string;
  kind?: string;
  user_id?: string;
  client_id?: string;
  amount?: number;
  gateway?: string;
  location_id?: string;
  payment_method_id?: string;
  device_id?: string;
  external_transaction_id?: string;
  haravan_transaction_id?: string;
  transaction_type_id?: number;
  test?: boolean;
  receipt?: string;
  created_user?: string;
  payment_details?: string;
  send_email?: boolean;
  auth_code?: string;
}
