/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OrderShippingAddressView } from './orderShippingAddressView';
import type { OrderLineItemView } from './orderLineItemView';
import type { OrderShippingLineView } from './orderShippingLineView';
import type { OrderNoteAttributeView } from './orderNoteAttributeView';
import type { OrderTransactionView } from './orderTransactionView';
import type { OrderDiscountCodeView } from './orderDiscountCodeView';
import type { OrderViewFinancialStatus } from './orderViewFinancialStatus';
import type { OrderBillingAddressView } from './orderBillingAddressView';
import type { OrderViewConfirmedStatus } from './orderViewConfirmedStatus';
import type { OrderViewCancelledStatus } from './orderViewCancelledStatus';
import type { OrderViewClosedStatus } from './orderViewClosedStatus';
import type { OrderViewFulfillmentStatus } from './orderViewFulfillmentStatus';
import type { OrderViewOrderProcessingStatus } from './orderViewOrderProcessingStatus';

export interface OrderView {
  name?: string;
  id?: string;
  currency?: string;
  source?: string;
  tags?: string;
  token?: string;
  user_id?: string;
  note?: string;
  total_price?: number;
  shipping_address?: OrderShippingAddressView;
  order_number?: string;
  email?: string;
  gateway?: string;
  utm_term?: string;
  location_name?: string;
  order_code?: string;
  cart_token?: string;
  line_items?: OrderLineItemView[];
  location_id?: string;
  shipping_lines?: OrderShippingLineView[];
  note_attributes?: OrderNoteAttributeView[];
  transactions?: OrderTransactionView[];
  discount_codes?: OrderDiscountCodeView[];
  landing_site?: string;
  referring_site?: string;
  utm_content?: string;
  source_name?: string;
  landing_site_ref?: string;
  utm_source?: string;
  utm_campaign?: string;
  utm_medium?: string;
  financial_status?: OrderViewFinancialStatus;
  billing_address?: OrderBillingAddressView;
  is_deleted?: boolean;
  device_id?: string;
  contact_email?: string;
  gateway_code?: string;
  total_tax?: number;
  taxes_included?: boolean;
  confirmed_status?: OrderViewConfirmedStatus;
  cancelled_reason?: string;
  cancelled_status?: OrderViewCancelledStatus;
  total_discounts?: number;
  closed_at?: string;
  subtotal_price?: number;
  confirmed_at?: string;
  cancelled_at?: string;
  confirm_user?: string;
  total_weight?: number;
  browser_ip?: string;
  checkout_token?: string;
  cancel_reason?: string;
  closed_status?: OrderViewClosedStatus;
  buyer_accepts_marketing?: boolean;
  total_line_items_price?: number;
  processing_method?: string;
  fulfillment_status?: OrderViewFulfillmentStatus;
  order_processing_status?: OrderViewOrderProcessingStatus;
}
