/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderViewCancelledStatus = typeof OrderViewCancelledStatus[keyof typeof OrderViewCancelledStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderViewCancelledStatus = {
  uncancelled: 'uncancelled',
  cancelled: 'cancelled',
} as const;
