/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OrderLineItemViewFulfillmentStatus } from './orderLineItemViewFulfillmentStatus';

export interface OrderLineItemView {
  name?: string;
  id?: string;
  type?: string;
  title?: string;
  price?: number;
  sku?: string;
  grams?: number;
  barcode?: string;
  vendor?: string;
  variant_id?: number;
  variant_title?: string;
  product_id?: string;
  quantity?: number;
  price_original?: number;
  gift_card?: boolean;
  fulfillment_status?: OrderLineItemViewFulfillmentStatus;
  not_allow_promotion?: boolean;
  requires_shipping?: boolean;
  taxable?: boolean;
  fulfillment_service?: string;
  fulfillable_quantity?: number;
  image_src?: string;
  price_promotion?: number;
  total_discount?: number;
  product_exists?: boolean;
  ma_cost_amount?: number;
  actual_price?: number;
}
