/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderViewFulfillmentStatus = typeof OrderViewFulfillmentStatus[keyof typeof OrderViewFulfillmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderViewFulfillmentStatus = {
  fulfilled: 'fulfilled',
  partial: 'partial',
  restocked: 'restocked',
  unfulfilled: 'unfulfilled',
} as const;
