/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderViewOrderProcessingStatus = typeof OrderViewOrderProcessingStatus[keyof typeof OrderViewOrderProcessingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderViewOrderProcessingStatus = {
  pending: 'pending',
  processing: 'processing',
  self_delivery: 'self_delivery',
  completed: 'completed',
  failed: 'failed',
  cancel: 'cancel',
} as const;
