/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface OrderDiscountCodeView {
  id?: string;
  type?: string;
  amount?: number;
  code?: string;
  isCouponCode?: boolean;
}
