/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface OrderBillingAddressView {
  name?: string;
  id?: string;
  country?: string;
  address2?: string;
  districtCode?: string;
  lastName?: string;
  countryCode?: string;
  provinceCode?: string;
  wardCode?: string;
  firstName?: string;
  address1?: string;
  phone?: string;
  company?: string;
  ward?: string;
  zip?: string;
  city?: string;
  district?: string;
  province?: string;
  defaultAddress?: boolean;
}
