/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type OrderLineItemViewFulfillmentStatus = typeof OrderLineItemViewFulfillmentStatus[keyof typeof OrderLineItemViewFulfillmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderLineItemViewFulfillmentStatus = {
  unfulfilled: 'unfulfilled',
  partially_fulfilled: 'partially_fulfilled',
  fulfilled: 'fulfilled',
  not_fulfilled: 'not_fulfilled',
} as const;
