/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ResultSupplierView } from './resultSupplierView';

export interface PagedResponseSupplierView {
  result?: ResultSupplierView;
}
