/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ProductImageResponse } from './productImageResponse';
import type { ProductOptionResponse } from './productOptionResponse';
import type { ProductVariantResponse } from './productVariantResponse';

export interface ProductClientResponse {
  body_html?: string;
  created_at?: string;
  handle?: string;
  id?: string;
  product_type?: string;
  published_at?: string;
  published_scope?: string;
  template_suffix?: string;
  title?: string;
  updated_at?: string;
  vendor?: string;
  not_allow_promotion?: boolean;
  available?: boolean;
  tags?: string;
  sole_quantity?: number;
  images?: ProductImageResponse[];
  image?: ProductImageResponse;
  options?: ProductOptionResponse[];
  variants?: ProductVariantResponse[];
}
