/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ProductImageView {
  position?: number;
  id?: string;
  filename?: string;
  createdAt?: string;
  src?: string;
  productId?: string;
  updatedAt?: string;
  variantIds?: number[];
}
