/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ProductView } from './productView';

export interface ProductInventoryView {
  id?: number;
  title?: string;
  price?: number;
  sku?: string;
  barcode?: string;
  product?: ProductView;
  qty_onhand?: number;
  qty_available?: number;
  compare_at_price?: number;
  qty_commited?: number;
  qty_incoming?: number;
}
