/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ProductVariantRequest } from './productVariantRequest';
import type { ProductOptionRequest } from './productOptionRequest';

export interface ProductRequest {
  /** @minLength 1 */
  title: string;
  bodyHtml?: string;
  bodyPlain?: string;
  vendor?: string;
  productType?: string;
  tags?: string;
  templateSuffix?: string;
  publishedAt?: string;
  publishedScope?: string;
  variants?: ProductVariantRequest[];
  options?: ProductOptionRequest[];
  onlyHideFromList?: boolean;
  notAllowPromotion?: boolean;
}
