/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { InventoryRequest } from './inventoryRequest';

export interface ProductVariantRequest {
  title?: string;
  /** @minimum 0 */
  price?: number;
  sku?: string;
  barcode?: string;
  /** @minimum 0 */
  grams?: number;
  inventories?: InventoryRequest[];
  taxable?: boolean;
  option1?: string;
  option2?: string;
  option3?: string;
  /** @minimum 0 */
  compare_at_price?: number;
  /** @minimum 0 */
  cost_price?: number;
  /** @minimum 0 */
  inventory_quantity?: number;
  inventory_policy?: string;
  inventory_management?: string;
  is_tracking_inventory?: boolean;
  allow_purchase_when_sold_out?: boolean;
  requires_shipping?: boolean;
}
