/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ProductVariantView } from './productVariantView';
import type { ProductOptionView } from './productOptionView';
import type { ProductImageView } from './productImageView';

export interface ProductView {
  id?: string;
  handle?: string;
  variants?: ProductVariantView[];
  options?: ProductOptionView[];
  tags?: string;
  title?: string;
  createdAt?: string;
  images?: ProductImageView[];
  vendor?: string;
  productType?: string;
  publishedAt?: string;
  templateSuffix?: string;
  publishedScope?: string;
  updatedAt?: string;
  bodyHtml?: string;
  bodyPlain?: string;
  notAllowPromotion?: boolean;
  onlyHideFromList?: boolean;
}
