/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ProductVariantResponse {
  barcode?: string;
  compare_at_price?: string;
  grams?: number;
  id?: number;
  inventory_management?: string;
  inventory_policy?: string;
  option1?: string;
  option2?: string;
  option3?: string;
  position?: number;
  price?: string;
  product_id?: string;
  requires_shipping?: boolean;
  sku?: string;
  taxable?: boolean;
  title?: string;
  updated_at?: string;
  inventory_quantity?: number;
  old_inventory_quantity?: number;
  image_id?: string;
  weight?: number;
  available?: boolean;
  weight_unit?: string;
}
