/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { InventoryAdvanceView } from './inventoryAdvanceView';

export interface ProductVariantView {
  position?: number;
  id?: number;
  title?: string;
  inventoryAdvance?: InventoryAdvanceView;
  inventoryQuantity?: number;
  inventoryManagement?: string;
  createdAt?: string;
  option2?: string;
  imageId?: string;
  option3?: string;
  price?: number;
  sku?: string;
  option1?: string;
  grams?: number;
  barcode?: string;
  productId?: string;
  compareAtPrice?: number;
  inventoryPolicy?: string;
  updatedAt?: string;
  requiresShipping?: boolean;
  taxable?: boolean;
}
