/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ProvinceDetailsDTO {
  code?: string;
  countryId?: number;
  id?: number;
  name?: string;
}
