/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserView } from './userView';
import type { ErrorField } from './errorField';

export interface RestResponseUserView {
  message?: string;
  code?: number;
  data?: UserView;
  errors?: ErrorField[];
}
