/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SupplierView } from './supplierView';
import type { ErrorField } from './errorField';

export interface RestResponseSupplierView {
  message?: string;
  code?: number;
  data?: SupplierView;
  errors?: ErrorField[];
}
