/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResponseCustomerAddressView } from './pagedResponseCustomerAddressView';
import type { ErrorField } from './errorField';

export interface RestResponsePagedResponseCustomerAddressView {
  message?: string;
  code?: number;
  data?: PagedResponseCustomerAddressView;
  errors?: ErrorField[];
}
