/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CountryResponseDTO } from './countryResponseDTO';
import type { ErrorField } from './errorField';

export interface RestResponseCountryResponseDTO {
  message?: string;
  code?: number;
  data?: CountryResponseDTO;
  errors?: ErrorField[];
}
