/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResponseProductClientResponse } from './pagedResponseProductClientResponse';
import type { ErrorField } from './errorField';

export interface RestResponsePagedResponseProductClientResponse {
  message?: string;
  code?: number;
  data?: PagedResponseProductClientResponse;
  errors?: ErrorField[];
}
