/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResponseItemView } from './pagedResponseItemView';
import type { ErrorField } from './errorField';

export interface RestResponsePagedResponseItemView {
  message?: string;
  code?: number;
  data?: PagedResponseItemView;
  errors?: ErrorField[];
}
