/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResponseOrderView } from './pagedResponseOrderView';
import type { ErrorField } from './errorField';

export interface RestResponsePagedResponseOrderView {
  message?: string;
  code?: number;
  data?: PagedResponseOrderView;
  errors?: ErrorField[];
}
