/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShoppingCartDTO } from './shoppingCartDTO';
import type { ErrorField } from './errorField';

export interface RestResponseShoppingCartDTO {
  message?: string;
  code?: number;
  data?: ShoppingCartDTO;
  errors?: ErrorField[];
}
