/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { RestResponseMapStringEmployeeViewData } from './restResponseMapStringEmployeeViewData';
import type { ErrorField } from './errorField';

export interface RestResponseMapStringEmployeeView {
  message?: string;
  code?: number;
  data?: RestResponseMapStringEmployeeViewData;
  errors?: ErrorField[];
}
