/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderResult } from './createOrderResult';
import type { ErrorField } from './errorField';

export interface RestResponseCreateOrderResult {
  message?: string;
  code?: number;
  data?: CreateOrderResult;
  errors?: ErrorField[];
}
