/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResponseEmployeeView } from './pagedResponseEmployeeView';
import type { ErrorField } from './errorField';

export interface RestResponsePagedResponseEmployeeView {
  message?: string;
  code?: number;
  data?: PagedResponseEmployeeView;
  errors?: ErrorField[];
}
