/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { RestResponseMapStringCustomerViewData } from './restResponseMapStringCustomerViewData';
import type { ErrorField } from './errorField';

export interface RestResponseMapStringCustomerView {
  message?: string;
  code?: number;
  data?: RestResponseMapStringCustomerViewData;
  errors?: ErrorField[];
}
