/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeGroupView } from './employeeGroupView';
import type { Sort } from './sort';

export interface ResultEmployeeGroupView {
  content?: EmployeeGroupView[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  sorts?: Sort[];
}
