/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerView } from './customerView';
import type { Sort } from './sort';

export interface ResultCustomerView {
  content?: CustomerView[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  sorts?: Sort[];
}
