/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SegmentRequestType } from './segmentRequestType';

export interface SegmentRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  type: SegmentRequestType;
  /**
   * @minLength 0
   * @maxLength 5000
   */
  definition?: string;
}
