/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ShippingAddressRequest {
  address?: string;
  city?: string;
  zipCode?: string;
  company?: string;
  countryId?: number;
  provinceId?: number;
  districtId?: number;
  wardId?: number;
}
