/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShoppingCartViewAttributes } from './shoppingCartViewAttributes';
import type { CartItemView } from './cartItemView';

export interface ShoppingCartView {
  id?: string;
  attributes?: ShoppingCartViewAttributes;
  item_count?: number;
  token?: string;
  note?: string;
  total_price?: number;
  customer_id?: string;
  location_id?: string;
  items?: CartItemView[];
  total_weight?: number;
  requires_shipping?: boolean;
}
