/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CartItemDTO } from './cartItemDTO';
import type { ShoppingCartDTOAttributes } from './shoppingCartDTOAttributes';

export interface ShoppingCartDTO {
  id?: string;
  token?: string;
  item_count?: number;
  total_price?: number;
  items?: CartItemDTO[];
  attributes?: ShoppingCartDTOAttributes;
}
