/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface SupplierRequest {
  first_name?: string;
  last_name?: string;
  /** @minLength 1 */
  supplier_name: string;
  phone?: string;
  email?: string;
  status: number;
  zip_code?: string;
  country_id?: number;
  location?: string;
  address?: string;
  province_id?: number;
  district_id?: number;
  city?: string;
  ward_id?: number;
  company?: string;
  tax_code?: string;
  notes?: string;
  tags?: string;
  contact_name?: string;
  postal_zip_code?: string;
}
