/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface SupplierView {
  location?: string;
  id?: string;
  address?: string;
  tags?: string;
  status?: number;
  last_name?: string;
  first_name?: string;
  phone?: string;
  company?: string;
  email?: string;
  city?: string;
  tax_code?: string;
  zip_code?: string;
  notes?: string;
  ward_id?: number;
  country_name?: string;
  province_id?: number;
  country_id?: number;
  district_id?: number;
  supplier_name?: string;
  total_purchase?: number;
  created_name?: string;
  created_date?: string;
  district_name?: string;
  province_name?: string;
  ward_name?: string;
  debt?: number;
}
