/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface TransactionRequest {
  id?: number;
  gateway?: string;
  transactionDate?: string;
  accountNumber?: string;
  subAccount?: string;
  code?: string;
  content?: string;
  transferType?: string;
  description?: string;
  transferAmount?: string;
  referenceCode?: string;
  accumulated?: string;
}
