/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserInfoResponseUser } from './userInfoResponseUser';

export interface UserInfoResponse {
  user?: UserInfoResponseUser;
  authority?: string;
  loginUrl?: string;
  domainHost?: string;
  basePath?: string;
  scopes?: string[];
  production?: boolean;
  webView?: boolean;
  newbie?: boolean;
  admin?: boolean;
}
