/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * demo-liquibase
 * Hannie Jewelry API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface UserView {
  id?: string;
  phone?: string;
  email?: string;
  is_owner?: boolean;
  role_type?: number;
  last_login_date?: string;
  status?: number;
  is_deleted?: boolean;
  roles?: string[];
  permissions?: string[];
}
